language: objective-c

## Setup

# Travis initializes git submodules before `install` runs

install:
    # - `xctool`, required to build the unit test and documentation targets
    #   nothing to do here because it's already installed on Travis

    # - `appledoc`, used to build documentation
    #   Force the usage of appledoc 2.1 until https://github.com/inkling/Subliminal/issues/71 is addressed
    - brew unlink appledoc
    - brew install https://raw.github.com/mxcl/homebrew/33aa810/Library/Formula/appledoc.rb

## Test matrix

env:
    matrix:
        - TEST_COMMAND=test:unit                TEST_SDK=6.1
        - TEST_COMMAND=test:unit                TEST_SDK=7.1

        - TEST_COMMAND=test:CI_unit

        - TEST_COMMAND=test:integration:iphone  TEST_SDK=6.1
        - TEST_COMMAND=test:integration:iphone  TEST_SDK=7.1

        - TEST_COMMAND=test:integration:ipad    TEST_SDK=6.1
        - TEST_COMMAND=test:integration:ipad    TEST_SDK=7.1

        - TEST_COMMAND=build_docs

## Test script

script: rake $TEST_COMMAND
